[package]
name = "todo-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = {version = "0.29.0", features = ["all-widgets"]}
color-eyre = "0.6.3"
dirs = "5.0"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = "1.0"
thiserror = "1.0"
tempdir = "0.3"
uuid = { version = "1.10", features = ["serde", "v4"] }
tui-textarea = "0.7.0"
chrono = { version = "0.4", features = ["serde"] }
textwrap = { version = "0.16.2" }
dark-light = "2.0.0"
toml = { version = "1.0.3", features = ["parse", "display"] }
log = "0.4"
simplelog = "0.12"
strum = { version = "0.28", features = ["derive"] }

[features]
default = ["serde"]
serde = ["dep:serde"]
